# Generated by Django 2.2.7 on 2019-11-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegan_spider_app', '0002_auto_20191129_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.Unit'),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.Unit'),
        ),
    ]
