# Generated by Django 2.2.7 on 2019-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan_spider_app', '0002_auto_20191116_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
