# Generated by Django 2.2.7 on 2019-11-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegan_spider_app', '0003_auto_20191116_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='grams',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.Ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ingredients',
            field=models.ManyToManyField(through='vegan_spider_app.UserIngredient', to='vegan_spider_app.Ingredient'),
        ),
    ]
