# Generated by Django 2.2.7 on 2019-11-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan_spider_app', '0003_auto_20191129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
