# Generated by Django 2.2.7 on 2019-11-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegan_spider_app', '0004_auto_20191130_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_spider_app.Unit'),
        ),
    ]
